### ISSUE TITLE
Placing sturdy floor below travelnet to prevent falling

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#202] opened 2021-09-11 13:10 UTC
Huhhila ; SX 
Do we have in-game issue for falling from travelnet if there isn't a sturdy floor below it, whenever loading lags?

Yeah, known issue but I think not in any proper issue tracker... lag is not even requirement but can happen even when you already have area in cache.
I do remember fixing few shop floors with that problem and I remember someone else done that few times too. Somehow I remember you were talking about it when I fixed one shop floor last time...

**Comment by S-S-X** [comment] 2021-09-13 15:07
Good as in game task to mitigate immediate problems but root cause is not in game world but in minetest engine or travelnet mod.
Could try to see if teleporting player just bit higher helps. If it does not help then it is probably engine or slow network, there's no good way to fix that.

One could force sending blocks to player before teleport but that is rarely needed and would just cause useless traffic.
Another possibility would be to disable gravity for short time when teleporting but again not really fixing issue but dirty hack that also has potential to cause other problems.
If area loading is not problem then third possible option would be to make travelnet climbable to prevent player from falling out of it, again weird hacky way to work around problem. Probably best option but wont help in every situation.

**Comment by Klaranth** [comment] 2021-09-14 17:09
Here's a question, how do you place a travelnetbox  other than on top of a node?  Do we want to reward people who are forgetting that you can fall through?

**Comment by S-S-X** [comment] 2021-09-14 19:13
> Here's a question, how do you place a travelnetbox other than on top of a node? Do we want to reward people who are forgetting that you can fall through?

As simple answer you can either place travelnet to walls or simply remove node below it afterwards.

About rewarding people I don't get what you actually mean by that? Travelnet boxes however do have floor and players should not fall through but sometimes they will.

**Comment by Klaranth** [comment] 2021-09-14 22:10
> About rewarding people I don't get what you actually mean by that? Travelnet boxes however do have floor and players should not fall through but sometimes they will.

People get rewarded by fixing the floor, after they remove the node that keeps them inside ...

**Comment by S-S-X** [comment] 2021-09-15 14:16
This should probably be moved to https://github.com/mt-mods/travelnet/issues as bug report.
Not sure if being in game task here is helpful at all because these mistakes / accidents will happen and as in game task this cannot really be solved ever.

**Comment by S-S-X** [comment] 2022-01-28 12:54
Merging PR https://github.com/mt-mods/travelnet/pull/27 might also fix this issue if area loading is main problem here.

**Comment by Klaranth** [comment] 2022-01-31 18:21
baijin
#bug travelnets teleport you into the floor of the destination box, causing me to fall out underneath my small jumpship
1hit
That's why all of us with R1 jump-ships have some solid node under our tnets.  Mine have a beacon or airpump.
baijin
Good idea

**Comment by Klaranth** [comment] 2022-07-31 11:07
Huhhila
[in-game#202] consider player_model_bottom = -0.4 in minetest conf? (and test that with chicken mode too)

**Comment by OgelGames** [comment] 2023-06-25 12:12
Fixed by https://github.com/mt-mods/travelnet/commit/b20b8cdb6617ca0792896f4255e73b79a3d9938f

**Closed by OgelGames** 2023-06-25 12:12 UTC
Labels: Bug, Waiting
