### ISSUE TITLE
uncraftable: homedecor:glass_table_large_square

### ISSUE THREAD

**Issue by SwissalpS** [pandorabox-io/in-game#236] opened 2021-12-26 14:49 UTC

**Comment by SwissalpS** [comment] 2022-03-06 16:51
it is craftable, but the crafting guide does not display how on pandorabox

**Comment by SwissalpS** [comment] 2022-03-06 17:01
Then trying to make homedecor:skylight does not work. Recipe is shown but neither craftingtable nor autocrafter actually craft it.

**Comment by SwissalpS** [comment] 2022-03-06 17:05
After having had some large tabletops on crafting grid, they don't stack anymore with the stack user had taken them from.

**Comment by Klaranth** [comment] 2022-04-03 11:27
wsor 
Can this please be closed as invalid? proof: https://github.com/mt-mods/homedecor_modpack/issues/25

Huhhila
Hmm, homedecor:glass_table_large is not homedecor:glass_table_large_square

wsor 
how is that relevant?
issue reported is that "homedecor:glass_table_large_square" is not craftable, i proved that it is
if that one is not craftable, please make a issue on the homedecor issue tracker
at least from a quick search "homedecor:glass_table_large" is not even a valid node name?

Huhhila
well the small -> large crafting rules refers to that at least on pandorabox (including test server where you can /give broken recipe items to yourself)
However digging a placed homedecor:glass_table_large results in a homedecor:glass_table_large_square in the inventory. Another instance of item aliasing being broken as a concept, or something else?

https://github.com/mt-mods/homedecor_modpack/blob/16bcc35ba28c5787a2742e2f965c83c259d3ac71/homedecor_tables/misc.lua#L123,L126

Apparently large wooden tabletops also affected. Root cause appears to be incorrect/unsupported chained usage of register_alias. I'd recommend removing any dependency on register_alias at all on newly placed items, only use it for existing item compatibility.

Huhhila
My suggested fix is to change the register_craft calls to refer to actual item instead of some legacy cruft.
=> maybe reopen homedecor_modpack/issues/25 with that suggested fix.

wsor 
Or make a seperate issue

**Comment by Klaranth** [comment] 2022-06-19 18:12
<Huhhila> regarding #236 the recipes to be fixed are at https://github.com/mt-mods/homedecor_modpack/blob/16bcc35ba28c5787a2742e2f965c83c259d3ac71/homedecor_roofing/init.lua#L325,L331 and similarly any mentions of wood_table_large and glass_table_large in homedecor_tables/misc.lua (if aliases are kept as they are)

**Comment by Klaranth** [comment] 2023-06-24 08:42
@OgelGames Any update?

**Comment by OgelGames** [comment] 2023-06-24 11:12
I think this commit fixed it: https://github.com/mt-mods/homedecor_modpack/commit/b4297d68a0d9e07f933911643f6c6e331c2dbd4e

I don't even remember assigning myself to this one 🤔

**Closed by OgelGames** 2023-06-24 11:12 UTC
Labels: WIP
