### ISSUE TITLE
Node-deployer to speak digiline

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#96] opened 2021-05-29 19:34 UTC
Check #81 for earlier discussion on CLU and Digiline updates on machines.

@dennisjenkins75
I would very much like to see the node-breaker and node-deployer capable to speaking digiline. Its cumbersome to have an almost pure-digiline machine that needs digiline<->mesecons interface to use these machines.

@S-S-X
In my opinion adding digiline interface for devices that currently accept mesecons signal (for basic on/off control) would be fine if digiline control allows exactly same binary functions like "enable", "disable" and possibly "activate" (last one being similar to mesecons on/off pulse action, maybe there's better word for that...).

If adding more advanced functionality than what mesecons can practically provide with binary input then it depends on actual functionality added, there's no generic "one size fits all" answer. In this case it should be separate discussion for each device.

**Comment by OgelGames** [comment] 2021-05-30 03:21
Duplicate of #95

**Comment by Klaranth** [comment] 2021-05-30 08:45
As SX stated : 
In this case it should be separate discussion for each device.

#95 and #96 may very well end up in the same PR, but for now let's keep the discussions separate.

**Closed** 2024-05-26 14:31 UTC
Labels: Enhancement, TODO
