### ISSUE TITLE
Interserver contest idea

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#182] opened 2021-08-21 19:58 UTC
SX 
New, bit wider, contest idea: contest between servers, who can make legit update restart most complicated topic :P
Community PR event :)

**Comment by OgelGames** [comment] 2021-08-22 04:31
I'm not sure this was intended to be a serious idea...

**Comment by Klaranth** [comment] 2021-08-22 09:06
Original Poster should be aware by now that whatever is added to #ideas ends up here, regardless of the reason of being posted.  If he does not want to see it end up here, Original Poster should find another channel to litter. :P

**Comment by S-S-X** [comment] 2021-08-22 16:34
> I'm not sure this was intended to be a serious idea... (note the `:P` in the original message)

It is true that whole thing was more joke than serious suggestion but still as wider community event something like this could actually be useful for development. There's little bit of truth even in this joke...

Getting more players to join other servers to take a closer look what they have and then vote for nice things and differences in processes or functionality, in theory it would benefit larger community that is not just closed server community but modding and engine specific community.

It probably would be difficult to actually successfully pull off something like this but if event like this would succeed at least on some level it would for sure bump up generic awareness and help smaller groups work together a lot more efficiently focusing on similar problems and improvements.

**Comment by Klaranth** [comment] 2021-08-22 23:47
>There's little bit of truth even in this joke...

Which is why even jokes get placed here. Cause one never know where a silly joke may lead to. :)

**Comment by Klaranth** [comment] 2021-08-29 07:16
SX
I do admit that it was not really serious idea first but bringing it here to see if anyone could see something like that somehow possible, fun or useful. I've added comments about how I could see community PR events like that possibly useful thing, just no idea how something like could actually be efficiently arranged.

**Comment by S-S-X** [comment] 2022-04-23 19:51
Closing as probably wont happen anytime soon, this requires a lot of communication between server admins and preferably on both servers small contributor groups who are able to communicate and coordinate thing like this together.

Things like this might gain some more traction if "gap" between different servers can be narrowed by other means and that alone requires a lot of time and work to be done.

**Closed by S-S-X** 2022-04-23 19:51 UTC
Labels: Possible close, Event idea
