### ISSUE TITLE
Identical recipes 

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#209] opened 2021-09-27 11:16 UTC
Huhhila
xpanes:trapdoor_steel_bar and glass_stained:pane_bar_single have identical recipe, people have been mentioning that for quite a while now

**Comment by Klaranth** [comment] 2021-09-27 11:17
OgelGames
https://github.com/pandorabox-io/pandorabox.io/issues/421#issuecomment-609597201

**Comment by OgelGames** [comment] 2021-09-28 08:31
Will be fixed by https://github.com/v-rob/glass_stained/pull/1, closing this issue as it's a duplicate of pandorabox-io/pandorabox.io#421 (which is where bug issues should be submitted anyway)

**Closed by OgelGames** 2021-09-28 08:31 UTC
Labels: Addition
