### ISSUE TITLE
Disable glider in Space  

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#158] opened 2021-07-24 11:35 UTC
ThinkSome
Disable glider in vacuum (y>5000?). There's nothing to glide on!
brlj
Except in mars caves, which is above y>5000
ThinkSome
Right, so glider should work y<5000 and 10000<y<11000 or what was the mars height.

Hedgehog 
There are solar winds ....

**Comment by S-S-X** [comment] 2021-07-24 16:35
I do kind of like idea allowing gliders to be used only in atmosphere, not sure how well that would actually work but it sounds way more correct approach.
In deep space you also do not need glider for anything because you can just enable fly, however it would make gravity + vacuum more correct without really disabling lot of functionality.

**Comment by OgelGames** [comment] 2021-09-15 08:37
Duplicate of #117

**Closed by OgelGames** 2021-09-15 08:37 UTC
Labels: Enhancement, Controversial
