### ISSUE TITLE
Spectator mod request

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#205] opened 2021-09-18 17:07 UTC
wsor ; SX ; Huhhila  
Before I bother to make a github issue, what are thoughts on https://github.com/greenxenith/spectator being added to pandorasbox? It is used on undercore, and is rather useful for checking your surroundings.

Related : 
https://github.com/pandorabox-io/pandorabox.io/issues/461
https://github.com/pandorabox-io/in-game/issues/6 

@BuckarooBanzai Request for your input on 461.

**Comment by OgelGames** [comment] 2021-09-19 04:03
Duplicate of pandorabox-io/pandorabox.io#461

See https://github.com/pandorabox-io/pandorabox.io/issues/461#issuecomment-917862719

**Closed by OgelGames** 2021-09-19 04:03 UTC
Labels: Duplicate, Mod request
