### ISSUE TITLE
Improve on infinite diamond generator

### ISSUE THREAD

**Issue by Klaranth** [pandorabox-io/in-game#259] opened 2022-01-16 20:01 UTC
baijin
Putting wood charcoal through the refinery to create a slurry, which goes through an extractor to chemically separate the carbon molecules and chains, and another extractor, then a centrifuge to remove the radioactive carbon isotopes, then it turns into coal dust

**Comment by SwissalpS** [comment] 2022-01-16 22:00
https://github.com/pandorabox-io/in-game/issues/245

**Comment by Baigle** [comment] 2022-01-16 22:46
its not meant to be

**Comment by S-S-X** [comment] 2022-01-16 23:52
Pretty much same comment: bad idea as it further reduces items that can mostly be obtained through active work.
Exact duplicate of #245 with just different process details.

**Closed** 2022-04-23 21:27 UTC
Labels: Enhancement, Possible close, Lazifying
